---
deployment:
  tasks:
    - export DEPLOYPATH=/home/irelandc/coachruthjackson.com
    - /bin/mkdir -p "$DEPLOYPATH"
    - /usr/bin/rsync -a --exclude='.git' --exclude='.cpanel.yml' ./ "$DEPLOYPATH/"
